server:
  port: 9000
spring:
  application: paichong
  #datasource config
  druid:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: *
    password: *
    MaxActive: 10
    timeBetweenEvictionRunsMillis: 60000
    maxWait: 10000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    validationQuery: SELECT 1 from dual
mybatis:
  type-aliases-package: com.spider.extension.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml